### ISSUE TITLE
Tables broken in packaged manual

### ISSUE THREAD

**Issue by ghost** [OpenOrienteering/mapper-manual#33]
Need fix tables in distributed manual.

![Broken tables](http://hnng.moe/f/WUi)

Here are same pages in online manual, but it hasn't such mistakes
* http://www.openorienteering.org/mapper-manual/pages/file_menu.html
* http://www.openorienteering.org/mapper-manual/pages/edit_menu.html
* http://www.openorienteering.org/mapper-manual/pages/map_menu.html
* http://www.openorienteering.org/mapper-manual/pages/symbols_menu.html
* http://www.openorienteering.org/mapper-manual/pages/templates_menu.html

**Comment by Abbe98** [comment]
Do you know if there is any table that isn't broken? Seams like Markdown tables are not supported at all...

**Comment by dg0yt** [comment]
Markdown doesn't really support tables just for layout. IIRC every table needs a headline and gets borders, and this was a reason why I couldn't convert some HTML tables to markdown...

**Comment by dg0yt** [comment]
BTW, Github sometimes changes its Markdown features, https://github.com/blog/2333-a-formal-spec-for-github-flavored-markdown or simply https://github.com/blog/search?utf8=%E2%9C%93&q=markdown

Remember:
Manual repository: GitHub Flavored Markdown
Online manual website: Github pages (Jekyll + ???Markdown)
Packaged manual: Doxygen Markdown (with some preprocessing)

**Comment by Abbe98** [comment]
Doxygen supports markdown tables([ref](1)), although something is going on here. @dg0yt do you have a set date for 0.8? I would need to setup an Mapper dev environment to test this...

[1]:https://www.stack.nl/~dimitri/doxygen/manual/markdown.html#md_tables

**Comment by ghost** [comment]
> GFM enables the table extension, where an additional leaf block type is available.

Details - https://github.github.com/gfm/#tables-extension-

Think, I found some mistake in page sources: you forget add `Space`'s inside tables and atleast one additional row for get correct tables in Github Flavoured Markdown
* Single row table:
  ```
  | foo | bar |
  | --- | --- |
  ```
| foo | bar |
| --- | ---|

* Two row table:
```
| foo | bar |
| --- | --- |
| baz | bim |
```
| foo | bar |
| --- | ---|
| baz | bim |

* Three and more row table:
```
| foo | bar |
| --- | --- |
| baz | bim |
| on | off |
| in | out |
```
| foo | bar |
| --- | ---|
| baz | bim |
| on | off |
| in | out |

### Manual repository sources

Here is current (incorrect to GFM) source of single row tables on discussed pages
```
|![ ](../mapper-images/new.png)|**New**|**Ctrl+N**|This shows the dialog to create a [new map](new_map.md).|
```

|![ ](../mapper-images/new.png)|**New**|**Ctrl+N**|This shows the dialog to create a [new map](new_map.md).|

And here is correct table in GFM markup
```
| ![ ](../mapper-images/new.png) | **New** | **Ctrl+N** | This shows the dialog to create a [new map](new_map.md). |
| --- | --- | --- | --- |
| ... | ... | ... | ... |
```

| ![ ](../mapper-images/new.png) | **New** | **Ctrl+N** | This shows the dialog to create a [new map](new_map.md). |
| --- | --- | --- | --- |
| ... | ... | ... | ... |

**Comment by dg0yt** [comment]
It is not about space or number of rows, it is about
> every table needs a headline

And the GFM is the least relevant out of three renders here (only relevant for the immediate preview).

Tables are completely irrelevant when these pages are designed like http://www.openorienteering.org/mapper-manual/pages/view_menu.html.

**Comment by dg0yt** [comment]
Looking at GFM is misleading, because GFM is the least relevant out of three renders here (only relevant for the immediate preview). We need to respect the least common denominator.

- Every table needs a headline (the first line, followed the separator line `|-|...`).
- For doxygen:
  - Every table needs another line. Above "single row table" won't work.
  - Every table needs at least two columns.
  - Every table column needs at least one character (can be whitespace).

So the following works:
~~~
|![ ](../mapper-images/templates.png)|Template setup window|
|-|-|
| |Ctrl+Shift+9|

Switches the display of the [template setup window](templates.md#setup) on the map screen. This provides access to the functions required to open, scale, and position a template, and to close it.

| | Open template... |
|-|-|
| | |

Opens a template file directly without going through the setup window.
~~~

But the headlines are quite difficult to spot when there is no icon. IIRC that's one reason (beside simple edititing) why I changed some pages (e.g. http://www.openorienteering.org/mapper-manual/pages/view_menu.html) to not use tables at all, but proper Markdown headlines instead (side note: no images allowed by doxygen in h2):
~~~
#### Reopen template...

Shows the template reopen dialog where templates which have been opened and then closed before can be restored.
~~~

Resulting output in HTML, as displayed by Assistant on Windows (limited HTML capabilities):
![screenshot](https://user-images.githubusercontent.com/13567791/32767765-1e716e76-c915-11e7-9d4d-179e304b36ac.png)


I guess best thing to start with is that I convert to the last form by running regex replacements in my text editor.

**Comment by dg0yt** [comment]
> But the headlines are quite difficult to spot when there is no icon. IIRC that's one reason (beside simple edititing) why I changed some pages (e.g. http://www.openorienteering.org/mapper-manual/pages/view_menu.html) to not use tables at all, but proper Markdown headlines instead (side note: no images allowed by doxygen in h2)

Actually this is incorrect: doxygen does not allow images in any headline. We convert these h4 headlines to tables before passing them to markdown.

**Comment by Symbian9** [comment]
@dg0yt, also need fix shortcuts on "View Menu" page:
* https://github.com/OpenOrienteering/mapper-manual/blob/gh-pages/pages/view_menu.md

TODO:
* Now they look like `(Key)` and `Key`
* Need use style `*Key*`

**Comment by Symbian9** [comment]
I use **Ghostwriter** text editor for *Markdown* files editing, that support many widely used rendering styles
* https://github.com/wereturtle/ghostwriter/releases/tag/v1.5.0

Here are variants (including current) for organize shortcuts in manual
![Manual shotcuts](http://hnng.moe/f/WXB)

**Comment by dg0yt** [comment]
The issue "Tables broken in packaged manual" is solved and closed. Please move the unrelated stuff out of here. Maybe someone else wants to pick it up.

**Comment by Symbian9** [comment]
Moved unrelated to
* https://github.com/openorienteering/mapper-manual
